language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"
install:
  # Install everything required to test the project
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install -r requirements3.txt --use-mirrors; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '3.3' ]]; then pip install -r requirements.txt --use-mirrors; fi
script: nosetests 
